function pullVitalPathways(model,solution,workbook)

%Pull out the important biosynthetic and catabolic pathways 

%Do an FVA and FBA
[minFlux,maxFlux] = fluxVariability(model);

%Make a list of catabolic reactions
catabolic = {'rxn11938_c0'...
            ,'rxn02341_c0'...
            ,'rxn02480_c0'...
            ,'rxn03079_c0'...
            ,'rxn06696_c0'...
            ,'rxn03085_c0'...
            ,'rxn03020_c0'...
            ,'rxn03127_c0'...
            ,'HdrABC'...
            ,'Eha'...
            ,'rxn06299_c0'...
            ,'ATPS'...
            ,'rxn05209_c0'...
            ,'Fdh'...
            ,'Hdr_formate'...
            }';

[rxns,idx]=intersect(model.rxns,catabolic);
names = model.rxnNames(idx);
genes = model.grRules(idx);
formulas = printRxnFormula(model,rxns,'False');
fluxes = num2cell(solution.x(idx));
lb = num2cell(model.lb(idx));
ub = num2cell(model.ub(idx));
minFluxes = num2cell(minFlux(idx));
maxFluxes = num2cell(maxFlux(idx));
A = [rxns,fluxes,minFluxes,maxFluxes,formulas,genes,names,lb,ub];
xlswrite(workbook,A,'Catabolic','A2');

%Make a list of biosynthetic reactions
biosynthetic = {'CODH'...
                ,'Eha'...
                ,'Ehb'...
                ,'rxn00172_c0'...
                ,'rxn00175_c0'...
                ,'rxn05938_c0'...
                ,'rxn00250_c0'...
                ,'rxn00248_c0'...
                ,'rxn00249_c0'...
                ,'rxn00799_c0'...
                ,'SuccOR'...
                ,'rxn00285'...
                ,'rxn05939_c0'...
                ,'rxn00085_c0'...
                ,'rxn00187_c0'...
                ,'rxn00782_c0'...
                ,'rxn07191_c0'...
                ,'rxn01100_c0'...
                }';

[rxns,idx]=intersect(model.rxns,biosynthetic);
names = model.rxnNames(idx);
genes = model.grRules(idx);
formulas = printRxnFormula(model,rxns,'False');
fluxes = num2cell(solution.x(idx));
lb = num2cell(model.lb(idx));
ub = num2cell(model.ub(idx));
minFluxes = num2cell(minFlux(idx));
maxFluxes = num2cell(maxFlux(idx));
A = [rxns,fluxes,minFluxes,maxFluxes,formulas,genes,names,lb,ub];
xlswrite(workbook,A,'Biosynthetic','A2');            
