function model = convertNamesToIDs(model)

%%%%%%%%%%%%%%%
% Code to take the current "IDs", which are identical to the compound
% "names" and replace them with actual SEED IDs
% Current model has metSEEDID field, which has the SEED IDs for things
% where those exist. 
% For things without metSEEDID, add manual IDs (like I've done with
% reactions)

% First, replace all "_e0" and "_c0" with "[e0]" and "[c0]", including in
% reactions and reaction names. 
for i=1:length(model.mets)
model.mets{i} = regexprep(model.mets{i},'_c0','[c0]');
model.mets{i} = regexprep(model.mets{i},'_e0','[e0]');
model.metNames{i} = regexprep(model.metNames{i},'_c0','[c0]');
model.metNames{i} = regexprep(model.metNames{i},'_e0','[e0]');
end

for i=1:length(model.rxns)
model.rxns{i} = regexprep(model.rxns{i},'_c0','[c0]');
model.rxns{i} = regexprep(model.rxns{i},'_e0','[e0]');
model.rxnNames{i} = regexprep(model.rxnNames{i},'_c0','[c0]');
model.rxnNames{i} = regexprep(model.rxnNames{i},'_e0','[e0]');
end

% Loop that replaces names with IDs
for i = 1:length(model.mets)
    if model.metSEEDID{i}
        % Check which compartment ID it has and add that
        if regexp(model.mets{i},'\[e0\]')
            model.mets{i} = strcat(model.metSEEDID{i},'[e0]');
        elseif regexp(model.mets{i},'\[c0\]')
            model.mets{i} = strcat(model.metSEEDID{i},'[c0]');
        end
    end
end

% I believe these 3 have actual SEED IDs
[~,idx] = intersect(model.mets,{'Isopentenylphosphate[c0]';...
'sn-3-O-(Geranylgeranyl)glycerol_1-phosphate[c0]';...
'2,3-Bis-O-(geranylgeranyl)glycerol_1-phosphate[c0]'},'stable');
model.mets(idx) = {'cpd17039[c0]';'cpd02797[c0]';'cpd02824[c0]'};

% Specific cases, make up my own IDs
[~,idx] = intersect(model.mets,{...
'2-amino-2,3,7-trideoxy-D-lyxo-hept-6-ulosonate[c0]';...
'4-Amino-3-Dehydroquinate[c0]';...
'4-Amino-3-Dehydroshikimate[c0]';...
'4-Aminoshikimate[c0]';...
'4-amino-3-hydroxycyclohexa-1,5-diene-1-carboxylate[c0]';...
'gamma-Glutamyl-tyramine[c0]';...
'4-(hydroxymethyl)-2-furancarboxaldehyde-phosphate[c0]';...
'5-(aminomethyl)-3-furanmethanol-phosphate[c0]';...
'5-(aminomethyl)-3-furanmethanol-pyrophosphate[c0]';...
'4((4-(2-aminoethyl)phenoxy)methyl)-2-furanmethanamine[c0]';...
'UDP-2-acetamido-2-deoxy-3-oxo-glucuronate[c0]';...
'UDP-2-acetamido-3-amino-2,3-dideoxy-glucuronate[c0]';...
'UDP-2,3-diacetamido-2,3-dideoxy-glucuronate[c0]';...
'UDP-2,3-diacetamido-2,3-dideoxy-mannuronate[c0]';...
'UDP-3-acetamido-2,3-diaminomannuronate[c0]';...
'NDP-2-acetamino-2,4-dideoxy-5-O-methyl-hexos-5-ulo-1,5-pyranose[c0]';...
'NDP-(5S)-2-acetamido-2,4-dideoxy-5-O-methyl-alpha-L-erythro-hexos-5-ulo-1,5-pyranose[c0]';...
'Lipid_tetrasaccharide[c0]';...
'Lipid_tetrasaccharide_Thr[c0]';...
'Lipid_monosaccharide[c0]';...
'Lipid_disaccharide[c0]';...
'Lipid_trisaccharide[c0]';...
'Lipid_tetrasaccharide_Thr[e0]';...
'Flagellin[e0]';...
'Archaellin[e0]';...
'Membrane_lipid[c0]';...
'Archaetidylserine[c0]';...
'Saturated_CDP-archaeol[c0]';...
'Saturated_Archaetidylserine[c0]'...
},'stable');

model.mets(idx) = {...
%'2-amino-2,3,7-trideoxy-D-lyxo-hept-6-ulosonate[c0]'
'2ATDLH6U[c0]';...
%'4-Amino-3-Dehydroquinate[c0]'
'2A3DHQ[c0]';...
%'4-Amino-3-Dehydroshikimate[c0]'
'4A3DHS[c0]';...
%'4-Aminoshikimate[c0]'
'4ASKM[c0]';...
%'4-amino-3-hydroxycyclohexa-1,5-diene-1-carboxylate[c0]'
'4A3H15D1C[c0]';...
%'gamma-Glutamyl-tyramine[c0]'
'GGT[c0]';...
%'4-(hydroxymethyl)-2-furancarboxaldehyde-phosphate[c0]'
'4HM2FCP[c0]';...
%'5-(aminomethyl)-3-furanmethanol-phosphate[c0]'
'5AM3FMP[c0]';...
%'5-(aminomethyl)-3-furanmethanol-pyrophosphate[c0]'
'5AM3FMPP[c0]';...
%'4((4-(2-aminoethyl)phenoxy)methyl)-2-furanmethanamine[c0]'
'AEPM2FMA[c0]';...
%'UDP-2-acetamido-2-deoxy-3-oxo-glucuronate[c0]'
'U2A2D3OG[c0]';...
%'UDP-2-acetamido-3-amino-2,3-dideoxy-glucuronate[c0]'
'U2A3A23DDG[c0]';...
%'UDP-2,3-diacetamido-2,3-dideoxy-glucuronate[c0]'
'U23DA23DDG[c0]';...
%'UDP-2,3-diacetamido-2,3-dideoxy-mannuronate[c0]'
'U23DA23DDM[c0]';...
%'UDP-3-acetamido-2,3-diaminomannuronate[c0]'
'U3A23DAM[c0]';...
%'NDP-2-acetamino-2,4-dideoxy-5-O-methyl-hexos-5-ulo-1,5-pyranose[c0]'
'N2A24D5MH4U15P[c0]';...
%'NDP-(5S)-2-acetamido-2,4-dideoxy-5-O-methyl-alpha-L-erythro-hexos-5-ulo-1,5-pyranose_c0'
'N2A24D5MAEH5U15P[c0]';...
%'Lipid_tetrasaccharide[c0]'
'LIP4SUG[c0]';...
%'Lipid_tetrasaccharide_Thr[c0]'
'LIP4SUGT[c0]';...
%'Lipid_monosaccharide[c0]'
'LIP1SUG[c0]';...
%'Lipid_disaccharide[c0]'
'LIP2SUG[c0]';...
%'Lipid_trisaccharide[c0]'
'LIP3SUG[c0]';...
%'Lipid_tetrasaccharide_Thr[e0]'
'LIP4SUGT[e0]';...
%'Flagellin[e0]'
'FLGN[e0]';...
%'Archaellin[e0]'
'ARCN[e0]';...
%'Membrane_lipid[c0]'
'MEMLIP[c0]';...
%'Archaetidylserine[c0]'
'ARCHLS[c0]';...
%'Saturated_CDP-archaeol[c0]'
'SATARCHL[c0]';...
%'Saturated_Archaetidylserine[c0]'
'SATARCHLS[c0]'...
    };

% Fix a little snafu
[~,idx] = intersect(model.mets,'cod03760[c0]');
model.mets{idx} = 'cpd03760[c0]';

% Final step: remove the seed ID array, it's no longer necessary
model = rmfield(model,{'metSEEDID'});
    
end
