function drawVitalPathwayFluxes(model,solution)

%Take in the M.maripaludis model and its solution, print out the Paint4Net
%biographs for both the Biosynthetic and Catabolic pathways

%Catabolic
%Make a list of catabolic reactions
catabolic = {'rxn11938_c0'...
            ,'rxn02431_c0'...
            ,'rxn02480_c0'...
            ,'rxn03079_c0'...
            ,'rxn06696_c0'...
            ,'rxn03085_c0'...
            ,'rxn03020_c0'...
            ,'rxn03127_c0'...
            ,'HdrABC'...
            ,'Eha/Ehb'...
            ,'rxn06299_c0'...
            ,'ATPS'...
            ,'rxn05209_c0'...
            ,'Fdh'...
            ,'Hdr_formate'...
            }';
        
%Draw the catabolic biograph
draw_by_rxn(model,catabolic,'true','struc',{''},{''},solution.x);
%Biosynthetic
biosynthetic = {'CODH'...
                ,'Eha/Ehb'...
                ,'rxn00172_c0'...
                ,'rxn00175_c0'...
                ,'rxn05938_c0'...
                ,'rxn00250_c0'...
                ,'rxn00248_c0'...
                ,'rxn00249_c0'...
                ,'rxn00799_c0'...
                ,'SuccOR'...
                ,'rxn00285_c0'...
                ,'rxn05939_c0'...
                ,'rxn00085_c0'...
                ,'rxn00187_c0'...
                ,'rxn00782_c0'...
                ,'rxn07191_c0'...
                ,'rxn01100_c0'...
                }';
            
%Draw the biosynthetic biograph
draw_by_rxn(model,biosynthetic,'true','struc',{''},{''},solution.x);