function drawVitalPathwayFluxes(model,solution)

%Takes in the M.maripaludis model and an FBA solution, then uses the
%Paint4Net toolbox to create flux maps for the main reactions in both the
%biosynthetic and catabolic pathways
%
% INPUT
% model:  the M. maripaludis model, a COBRA Toolbox model structure
% solution: a flux distribution solution to the M. maripaludis model
% 
% Matthew Richards, 09/28/2015


%Catabolic
%Make a list of catabolic reactions
catabolic = {'rxn11938[c0]'...
            ,'rxn02431[c0]'...
            ,'rxn02480[c0]'...
            ,'rxn03079[c0]'...
            ,'rxn06696[c0]'...
            ,'rxn03085[c0]'...
            ,'rxn03020[c0]'...
            ,'rxn03127[c0]'...
            ,'HdrABC'...
            ,'Eha/Ehb'...
            ,'rxn06299[c0]'...
            ,'ATPS'...
            ,'rxn05209[c0]'...
            ,'Fdh'...
            ,'Hdr_formate'...
            }';
        
%Draw the catabolic biograph
draw_by_rxn(model,catabolic,'true','struc',{''},{''},solution.x);
%Biosynthetic
biosynthetic = {'CODH'...
                ,'Eha/Ehb'...
                ,'rxn00172[c0]'...
                ,'rxn00175[c0]'...
                ,'rxn05938[c0]'...
                ,'rxn00250[c0]'...
                ,'rxn00248[c0]'...
                ,'rxn00249[c0]'...
                ,'rxn00799[c0]'...
                ,'rxn00285[c0]'...
                ,'rxn05939[c0]'...
                ,'rxn00085[c0]'...
                ,'rxn00187[c0]'...
                ,'rxn00782[c0]'...
                ,'rxn07191[c0]'...
                ,'rxn01100[c0]'...
                ,'Tfr'...
                }';
            
%Draw the biosynthetic biograph
draw_by_rxn(model,biosynthetic,'true','struc',{''},{''},solution.x);