function [rxns,fluxes] = printMethanogenesisFluxes(model,solution,map_flag)

% Take in the M. maripaludis model and an FBA solution, then pull and print
% the fluxes of methanogenesis reactions. Optionally, also use Paint4Net to
% draw a flux map of the methanogenesis reactions.
%
% INPUT
% model: the M. maripaludis model, a COBRA Toolbox model structure
% solution: a flux distribution solution to the M. maripaludis model
%
% OPTIONAL INPUT
% map_flag: a bianary variable that, when set to true, uses Paint4Net to
% draw a flux map of the methanogenesis reactions. (Default = false)
%
% OUTPUT
% rxns: a list of the reactions that are part of methanogenesis in M.
% maripaludis, aka "The Wolfe Cycle"
% fluxes: a list of fluxes corresponding to the methanogenesis reactions in
% "rxns"
%
% Matthew Richards, 09/24/2015


% Check for map flag
if (nargin<3)
    map_flag = false;
end

% Specify the reactions we want
rxns = {...
% Step 1: CO2 -> Formyl-MFR
'rxn11938[c0]';...
% Step 2: Formyl-MFR -> Formyl-H4MPT
'rxn02431[c0]';...
% Step 3: Formyl-H4MPT -> Methenyl-H4MPT
'rxn02480[c0]';...
% Step 4: Methenyl-H4MPT -> Methylene-H4MPT
'rxn06696[c0]';...
% Alternative Step 4: Methenyl-H4MPT -> Methylene-H4MPT
'rxn03079[c0]';...
% Step 5: Methylene-H4MPT -> Methyl-H4MPT
'rxn03085[c0]';...
% Step 6: Methyl-H4MPT -> Methyl-CoM
'rxn03020[c0]';...
% Step 7: Methyl-CoM -> Methane
'rxn03127[c0]';...
% Step 8: CoM-S-S-CoB -> CoM
'HdrABC';...
% Alt step 8: Formate + CoM-S-S-CoB -> CoM
'Hdr_formate';...
% Fd_ox + H2 + Na+(out) -> Fd_red + H+ + Na+
'Eha/Ehb';...
% ATP Synthase
'ATPS';...
% Biosynthesis (CODH): CO2 + Fd_red -> CO + Fd_ox
'CODH';...
% Biosynthesis (ACS): Methyl-H4MPT + CO + CoA -> Acetyl-CoA + H4MPT
'ACS';...
% Biosynthesis (POR): CO2 + Acetyl-CoA + Fd_red -> CoA + Fd_ox + Pyruvate
'rxn05938[c0]';...
% Biosynthesis (Oxaloacetate formation): CO2 + ATP + Pyruvate ->
% Oxaloacetate + ADP
'rxn00250[c0]'};

% Create a string of reaction directions, so I know what way the reaction
% is specified and can correctly specify reaction direction
% Use 1 for forward, -1 for backwards
directions = [...
    % Step 1: CO2 -> Formyl-MFR (backwards)
    -1;...
    % Step 2: Formyl-MFR -> Formyl-H4MPT (backwards)
    -1;...
    % Step 3: Formyl-H4MPT -> Methenyl-H4MPT (backwards)
    -1;...
    % Step 4: Methenyl-H4MPT -> Methylene-H4MPT (forwards)
    1;...
    % Alternative Step 4: Methenyl-H4MPT -> Methylene-H4MPT (backwards)
    -1;...
    % Step 5: Methylene-H4MPT -> Methyl-H4MPT (forwards)
    1;...
    % Step 6: Methyl-H4MPT -> Methyl-CoM (forwards)
    1;...
    % Step 7: Methyl-CoM -> Methane (forwards)
    1;...
    % Step 8: CoM-S-S-CoB -> CoM (forwards)
    1;...
    % Alt. Step 8: CoM-S-S-CoB + Formate -> CoM (forwards)
    1;...
    % Ferredoxin Generator (forwards)
    1;...
    % ATP Synthase (forwards)
    1;...
    % CODH (forwards)
    1;...
    % ACS (forwards)
    1;...
    % POR (forwards)
    1;...
    % Oxaloacetate formation (forwards)
    1];

% Create Reaction Strings to store reaction shorthand
rxn_strings = {...
'CO2 -> Formyl-MFR';...
'Formyl-MFR -> Formyl-H4MPT';...
'Formyl-H4MPT -> Methenyl-H4MPT';...
'Methenyl-H4MPT -> Methylene-H4MPT (H2-utilizing)';...
'Methenyl-H4MPT -> Methylene-H4MPT (F420-utilizing)';...
'Methylene-H4MPT -> Methyl-H4MPT';...
'Methyl-H4MPT -> Methyl-CoM';...
'Methyl-CoM + CoB -> CoM-S-S-CoB + Methane';...
'H2 + Fd_ox + CoM-S-S-CoB -> Fd_red + CoB + CoM';...
'Formate + Fd_ox + CoM-S-S-CoB -> CO2 + Fd_red + CoB + CoM';...
'Fd_ox + H2 + 2 Na+(out) -> Fd_red + H+ + 2 Na+';...
'4 Na+(out) + ADP + Phosphate -> ATP + 4 Na+';...
'CO2 + Fd_red -> CO + Fd_ox';...
'Methyl-H4MPT + CO + CoA -> Acetyl-CoA + H4MPT';...
'CO2 + Acetyl-CoA + Fd_red -> CoA + Fd_ox + Pyruvate';...
'CO2 + ATP + Pyruvate -> Oxaloacetate + ADP'};
% Intersect those reactions with the model, but keep it in the order of rxns
[~,~,idxB] = intersect(rxns,model.rxns,'stable');

% Use the index to pull out fluxes
fluxes = solution.x(idxB);

for i=1:length(rxns)
% Print it all out in pretty format
fprintf('\n%s (%s): %0.2f',rxn_strings{i},rxns{i},fluxes(i)*directions(i));
end
fprintf('\n\n')

if map_flag
    all_rxns = findMetSynPath(model,'cpd01024[e0]',solution,{'biomass0'},0.1);
    drawRxnsMap(model,all_rxns,solution);
end